os: linux

language: php

cache:
  apt: true
  directories:
    - .cache
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
  # Test against the highest/lowest supported PHPCS and WPCS versions.
  # Using WPCS 'master' for the last stable release.
  - PHPCS_BRANCH="dev-master" WPCS="dev-master" PHPLINT=1
  - PHPCS_BRANCH="dev-master" WPCS="2.3.0"
  - PHPCS_BRANCH="3.6.0" WPCS="dev-master"
  - PHPCS_BRANCH="3.6.0" WPCS="2.3.0"

# Define the stages used.
# For non-PRs, only the sniff, ruleset and quicktest stages are run.
# For pull requests and merges, the full script is run (skipping quicktest).
# Note: for pull requests, "develop" should be the base branch name.
# See: https://docs.travis-ci.com/user/conditions-v1
stages:
  - name: quicktest
    if: type = push AND branch NOT IN (master, develop)
  - name: test
    if: branch IN (master, develop)

jobs:
  fast_finish: true
  include:
    #### QUICK TEST STAGE ####
    # This is a much quicker test which only runs the unit tests and linting against low/high
    # supported PHP/PHPCS/WPCS combinations.
    - stage: quicktest
      php: 7.4
      env: PHPCS_BRANCH="dev-master" WPCS="dev-master" PHPLINT=1
    - php: 7.4
      env: PHPCS_BRANCH="3.6.0" WPCS="2.3.0"
    - php: 5.4
      dist: trusty
      env: PHPCS_BRANCH="dev-master" WPCS="2.3.0" PHPLINT=1
    - php: 5.4
      dist: trusty
      env: PHPCS_BRANCH="3.6.0" WPCS="dev-master"

    #### TEST STAGE ####
    # Additional builds against PHP versions which need a different distro.
    - stage: test
      php: 8.0
      env: PHPCS_BRANCH="dev-master" WPCS="dev-master" PHPLINT=1
    - php: 8.0
      # PHPCS is only compatible with PHP 8.0 as of version 3.6.0.
      env: PHPCS_BRANCH="3.6.0" WPCS="2.3.0"
    - php: 5.5
      dist: trusty
      env: PHPCS_BRANCH="dev-master" WPCS="dev-master" PHPLINT=1
    - php: 5.5
      dist: trusty
      env: PHPCS_BRANCH="dev-master" WPCS="2.3.0"
    - php: 5.5
      dist: trusty
      env: PHPCS_BRANCH="3.6.0" WPCS="dev-master"
    - php: 5.5
      dist: trusty
      env: PHPCS_BRANCH="3.6.0" WPCS="2.3.0"
    - php: 5.4
      dist: trusty
      env: PHPCS_BRANCH="dev-master" WPCS="dev-master" PHPLINT=1
    - php: 5.4
      dist: trusty
      env: PHPCS_BRANCH="dev-master" WPCS="2.3.0"
    - php: 5.4
      dist: trusty
      env: PHPCS_BRANCH="3.6.0" WPCS="dev-master"
    - php: 5.4
      dist: trusty
      env: PHPCS_BRANCH="3.6.0" WPCS="2.3.0"

    # Test against WPCS unstable.
    - php: 7.4
      env: PHPCS_BRANCH="dev-master" WPCS="dev-develop"

    # Test against PHP nightly.
    - php: "nightly"
      env: PHPCS_BRANCH="dev-master" WPCS="dev-master" PHPLINT=1

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"
    - env: PHPCS_BRANCH="dev-master" WPCS="dev-develop"


before_install:
    # Speed up build time by disabling Xdebug.
    # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
    # https://twitter.com/kelunik/status/954242454676475904
    - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

    # On stable PHPCS versions, allow for PHP deprecation notices.
    # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
    - |
      if [[ $PHPCS_BRANCH != "dev-master" && $WPCS != "dev-develop" ]]; then
        echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      fi

    - export XMLLINT_INDENT="	"
    - export PHPCS_DIR=$(pwd)/vendor/squizlabs/php_codesniffer
    - export PHPCS_BIN=$(pwd)/vendor/bin/phpcs
    # Set the PHPCS version to test against.
    - travis_retry composer require squizlabs/php_codesniffer:${PHPCS_BRANCH} --no-update --no-suggest --no-scripts
    # Set the WPCS version to test against.
    - travis_retry composer require wp-coding-standards/wpcs:${WPCS} --no-update --no-suggest --no-scripts
    # For testing the YoastCS native sniffs, the rest of the packages aren't needed.
    - travis_retry composer remove phpcompatibility/phpcompatibility-wp phpcompatibility/php-compatibility --no-update

    - |
      if [[ $TRAVIS_PHP_VERSION == "nightly" || $TRAVIS_PHP_VERSION == "8.0" ]]; then
        travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
      else
        travis_retry composer install --prefer-dist --no-interaction
      fi

    # The DealerDirect Composer plugin script takes care of the installed_paths.
    - $PHPCS_BIN -i

script:
    # Lint the PHP files against parse errors.
    - if [[ "$PHPLINT" == "1" ]]; then composer lint; fi

    # Run the unit tests.
    - vendor/bin/phpunit --filter Yoast --bootstrap="$PHPCS_DIR/tests/bootstrap.php" $PHPCS_DIR/tests/AllTests.php
